### ISSUE TITLE
ARMA (Armor Addon) records don't copy 'Unknown 0' weight slider when copying as override

### ISSUE THREAD

**Issue by tr4wzified** [Mutagen-Modding/Mutagen#165]
![afbeelding](https://user-images.githubusercontent.com/55751269/101980359-fc2aed80-3c64-11eb-80ab-ea14b25372ac.png)
Pretty sure this is the TUDM Patcher copying it as override to add a footstep sound. Can replicate it with latest version of LotD

**Comment by Noggog** [comment]
Record in question, for reference is: 
`00107610 <NakedBodyManakin>`

So this is a more interesting one, as Mutagen is applying some custom simplifications in this specific area.

I interpreted this field as a "Weight Slider Enabled" field, and to be a boolean of whether the weight slider is enabled.  They store it in a weird way, though.  It's a byte, where 0 means off, and 2 means on.   

Tes5Edit reference:
https://github.com/TES5Edit/TES5Edit/blob/04b642ce47a6f67fbf47b749b0087355f45f9cb2/Core/wbDefinitionsTES5.pas#L6944

So, Mutagen's current route is to expose this as a boolean, where it's true if the byte value == 2.  But in LOTD, they put 1 (what does this even mean?).  So Mutagen sees that as false, but on exporting exports 0, as that's normally what it does when exporting false in this scenario.

Mutagen custom parsing code, for reference:
https://github.com/Noggog/Mutagen/blob/release/Mutagen.Bethesda.Skyrim/Records/Major%20Records/ArmorAddon.cs

I would be interested to hear if that value of 1 is viable/meaningful.  There is some notes on the Tes5Edit specification:
`// essentialy a number of world models for different weights (Enabled = 2 models _0.nif and _1.nif)`
Is this suggesting that 1 might be valid?  I'm not 100% sure I understand what they're getting at here

**Comment by Excinerus** [comment]
I would check if the corresponding world model name ends with "_1.nif" if it's neither a 0 or 2. as the weight slider requires such naming

**Comment by Noggog** [comment]
Ah, so it does have some viable application?   Sounds like it's more of an enum concept, then?
```
Off = 0x00,
ByFilename = 0x01,
On = 0x02,
```
Or something along those lines?

Are people able to do 0x05, for example, and require a `_5.nif` suffix?

Here's that same record, for reference:
![image](https://user-images.githubusercontent.com/24981326/101994962-2e474a00-3c7b-11eb-97c1-e351fa49dfa2.png)

**Comment by Excinerus** [comment]
no,  the correct values are 0 or 2, however it seems the game just tests for >0. you can either have a slider or not,  but in order to have a functional slider, the models file name has to end with _1.nif/_0.nif, because the engine will look for an other _0.nif/_1.nif.   Weight slider function by interpolating vertices positions between two references relying on that naming convention.

-a value different than 0 or 2 is a bad value, even if the file is named _0/1.nif there's no guarantee the other file exists or works. 
-a value >0 with a file not following the naming convention will cause a graphic glitch or a CTD.

In the shown case it's just a flag set to >1 and a corresponding _0/1.nif on a heavily tested mod. I would interpret that as an xEdit missclick that went unnoticed due to not resulting in an unwanted behavior.

after testing I suggest just keeping the value as is.

test results :
0 - slider disabled
1 - slider enabled
2 - slider enabled
3 - slider enabled

**Comment by Noggog** [comment]
Alright, so it sounds like there's a few moving parts here?
1)  The flag seems to be either on/off.  0 is off, and any other value is on?  2 is just the value it gets by most tools (CK/Tes5edit) give when turning it on?  So maybe technically workable with other values, but weird?
2)  The flag being on requires that a specific file pattern be implemented.  Whatever filename is specified for "Model FileName" must have a `_0.nif` OR `_1.nif`.  Whichever is specified, the other MUST exist, as the game engine is going to look for and interpolate it?   I imagine the typical pattern is to list _0.nif, while accompanying it with _1.nif.  Is it also okay to list _1.nif, and accompany it with _0.nif?

I'll probably change Mutagen to "pass along" the value, if I can, while maintaining the boolean exposed API.  

The other requirements/checks sound like a good candidate for the Analyzer project.

**Comment by Excinerus** [comment]
in skyrim.esm i've only seen a single record with a _0.nif instead of _1.nif. i vaguely remember having to set the model path to the _1.nif for it to work in LE.
all instances where the flag is enabled, it's set to 2.
3 means unknown0 & Enabled.

might want to check the implementation in Oblivion or FO4.   weight sliders in FO4 use a single model, that flag structure might be so because of that.

**Comment by Noggog** [comment]
Improved the passthrough of the underlying value, just to reduce change noise when other values are modified on Armor Addons.
Modifications to Weight Slider and/or new records will always result in 0 or 2, though

802968ebbbfdd39875819f87778d5b479555f64c
