### ISSUE TITLE
"Oblivion" was not present... for SkyrimSE?

### ISSUE THREAD

**Issue by focustense** [Mutagen-Modding/Mutagen#203]
I'm manually constructing a load order for SSE, with very simple code:

```c#
var loadOrderKeys = pluginNames.Select(pluginName => ModKey.FromNameAndExtension(pluginName));
var loadOrder = LoadOrder.Import<ISkyrimModGetter>(GameDataFolder, loadOrderKeys, GameRelease.SkyrimSE);
var environment =
    GameEnvironmentState<ISkyrimMod, ISkyrimModGetter>.Construct(GameRelease.SkyrimSE, GameDataFolder);
```

The last line throws: `System.Collections.Generic.KeyNotFoundException: 'The given key 'Oblivion' was not present in the dictionary.'`

There's nothing about Oblivion in my code and never has been.

I'm testing this on a totally vanilla load order (i.e. not running from Mod Organizer), so the value of `loadOrderKeys` here is: `Skyrim.esm`, `Update.esm`, `Dawnguard.esm`, `HearthFires.esm`, `Dragonborn.esm`.

The `GameDataFolder` also appears to be normal: `D:\\\\Games\\\\Steam\\steamapps\\common\\Skyrim Special Edition\\Data`

Where is this Oblivion message coming from and why?

**Comment by focustense** [comment]
Here's the full stack trace, in case that helps:

```
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Mutagen.Bethesda.Core.LinkInterfaceMapping.InterfaceToObjectTypes(GameCategory mode)
   at Mutagen.Bethesda.ImmutableLoadOrderLinkCache..ctor(IEnumerable`1 loadOrder, LinkCachePreferences prefs)
   at Mutagen.Bethesda.ImmutableLoadOrderLinkCache`2..ctor(IEnumerable`1 loadOrder, LinkCachePreferences prefs)
   at Mutagen.Bethesda.ILinkCacheExt.ToImmutableLinkCache[TMod,TModGetter](LoadOrder`1 loadOrder, LinkCachePreferences prefs)
   at Mutagen.Bethesda.GameEnvironmentState`2.Construct(GameRelease release, String gameFolderPath, LinkCachePreferences linkCachePrefs)
   at NPC_Bundler.MutagenAdapter.<>c__DisplayClass14_0.<Load>b__0() in D:\Projects\SSE Tools\NPC Bundler\MutagenAdapter.cs:line 48
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by Noggog** [comment]
Found it:
<https://github.com/Mutagen-Modding/Mutagen/blob/2a9362cfb219f04ab41e31cb872c07d871218867/Mutagen.Bethesda.Core/Links/Cache/ImmutableLoadOrderLinkCache.cs#L55>
I'll fix that up to throw an exception instead of falling back to Oblivion.

That brings up a few other thoughts about the code snippet.
`GameEnvironmentState` is meant to be a quick standalone bootstrapper to get a typical setup going connected to a users typical installation.  But you seem to be wanting to make a more custom environment? (limiting it to certain plugins, etc?).  I'd suggest either:
- Just using `GameEnvironmentState` as outlined [here](https://github.com/Mutagen-Modding/Mutagen/wiki/Game-Environment-Bootstrapper), and not constructing your own LoadOrder object.
- Constructing everything (LoadOrder + LinkCache) yourself to be to your custom specifications, and not using `GameEnvironmentState` at all.  ([just call .ToImmutableLinkCache on your loadOrder to get a link cache](https://github.com/Mutagen-Modding/Mutagen/wiki/LinkCache))

Lastly, just for convenience, there's a nice way to access the base master ModKeys without needing to construct them yourself:
`Implicits.BaseMasters.Skyrim(SkyrimRelease.SkyrimSE)`
I gotta write a wiki on that topic ^, still

**Comment by focustense** [comment]
It's important to construct the load order manually, not just because I want users to be able to customize it (although I do), but also because the program needs to be able to exclude its own generated plugin if that's found in the load order. Sorta like Wrye Bash not loading its own Bashed Patch.

I thought I _was_ constructing everything custom by using `LoadOrder.Import`. I guess I'm confused - if I'm passing a `GameRelease` parameter to `Construct`, why doesn't it just use that instead of inferring from somewhere else?

But the workaround of constructing the link cache explicitly and passing it to the normal constructor of `GameEnvironmentState` works - thanks. I do like the `GameEnvironmentState` as it's a convenient wrapper for several things I'll frequently access.

**Comment by Noggog** [comment]
> if I'm passing a GameRelease parameter to Construct, why doesn't it just use that instead of inferring from somewhere else?

It should be.  I can modify some internals to pass it along better

> I thought I was constructing everything custom by using LoadOrder.Import

You were making your own custom load order object, yes, but you weren't passing it to GameEnvironment.  So GameEnvironment systems was making its own typical load order object internally to use.

What you want is the full on `new GameEnvironmentState()` call like you're mentioning, and just giving it EVERYTHING.

> the program needs to be able to exclude its own generated plugin if that's found in the load order

That's an interesting point.  That's pretty typical that people want to do this, so perhaps I can add this as an option when using  `GameEnvironmentState.Typical.Skyrim(..., myModKeyToOmit)`  (https://github.com/Mutagen-Modding/Mutagen/issues/206)

That wouldn't solve the problem of wanting your users to be able to customize the load order to deviate from `Plugins.txt`.  You'd still have to construct manually like you're doing to get that functionality

**Comment by Noggog** [comment]
d942b35901f2231065aeb7d5ea723fdddd72ab5b
