### ISSUE TITLE
ESP compiler/decompiler

### ISSUE THREAD

**Issue by samdeane** [Mutagen-Modding/Mutagen#281]
Just wanted to point you at [this](https://github.com/elegantchaos/SkyrimCompiler) project.

It's not directly related, and I'm using my own code [to parse ESPs](https://github.com/elegantchaos/SwiftESP).

However the idea of a compiler/decompiler is really independent of the ESP backend, and is something that would benefit from a bit of discussion and peer review. Is it worth pursuing? Does the proposed format make sense? 

The ultimate goal is that an entire mod project (esp records, resources, and scripts) could be contained in a structured source directory, and tools could automatically package them up as BSAs and ESPs, including compiling the scripts.

**Comment by Noggog** [comment]
Hey!  Sounds very similar to the thought processes I had when starting Mutagen.  Way back in the day, I had planned to have conversion into json/xml format for the purposes of storing mods in a git repository be the introductory proof of concept project, before [Synthesis](https://github.com/Mutagen-Modding/Synthesis) and [Analyzers](https://github.com/Mutagen-Modding/Mutagen.Bethesda.Analyzers) cut in line and took over in the work queue.

I do think it's a worthwhile endeavor to get mods into source control.  A big part of that would be two-way converting esps to a text format like json/xml/other.  Being able to leverage Git would give developers a lot of power to experiment, branch, as well as potentially even merge conflicts with other developers in a way that I imagine is very tough right now with just storing/transferring zip files with the content.

# Mutagen Fulfillment Musings
As I mentioned, I do/did plan on giving the concept a stab one of these days. As a short blurb on how I would go about it if the time came:

Mutagen exposes classes/interfaces like these:
```cs
public interface INpcGetter
{
    ITranslatedStringGetter? Name { get; }
    float Height { get; }
    float Width { get; }
    IVirtualMachineAdapterGetter? VirtualMachineAdapter { get; }
    IObjectBoundsGetter ObjectBounds { get; }
    // ...
}
```
The parsing for how to expose that interface is handled for the user.  They just get an object with strongly typed fields to use without any worry about how it's fulfilled.  Notice, too, concepts like `FULL` being associated with `Name` is abstracted away as an esp format implementation detail.

Obviously we wouldn't want to hand-write the conversion from these interfaces to json, so either:
- Use normal C# serialization libraries like [Json.Net](https://www.newtonsoft.com/json) that turn C# classes into json and vice versa.  Classes already exist and have names, this just turns it into two-way json straight up.  This could get a basic `esp<->json` converter going extremely quick, I think.  Obviously might need some pruning and edge case handling, but.
- Use reflection to write our own json serializer.  We use C# and the defined classes to iterate all the fields in a mod object and decide how to write out json ourselves.
- Use the same code generation systems Mutagen uses for binary translation to make json translation alternatives.  This would take the most work, but would be the fastest as it requires zero reflection, and also can leverage speed increase and memory reduction potential by being an [overlay](https://github.com/Mutagen-Modding/Mutagen/wiki/Binary-Overlay).

Some other items to consider that Mutagen brings to the table for a project like this:
- Strongly typed interfaces/classes that can be used in existing serialization libraries, as mentioned
- Already has 99%* coverage with Skyrim/Oblivion, and will have Fallout within the month, I expect.  The systems are [tested to pass through](https://github.com/Mutagen-Modding/Mutagen/wiki/Testing) both ways with byte-by-byte accuracy.
- Handles and abstracts away [translated string systems](https://github.com/Mutagen-Modding/Mutagen/wiki/Translated-Strings)
- Equality/hash calls (needs a wee bit of correctness testing, still)
- "Translation Mask" concepts to selectively skip fields during serialization, equality, or copy calls. (docs not yet written)
- Handles FormID reindexing when masters change internally, powered by the [FormKey](https://github.com/Mutagen-Modding/Mutagen/wiki/ModKey%2C-FormKey%2C-FormLink#formkey) systems
- FormID iteration and remapping tech. (no docs yet).  Essentially can see all the FormIDs that exist within a mod, as well as give the system a `Map<FormKey, FormKey>` and it'll replace them appropriately
- [FormID persistence systems](https://github.com/Mutagen-Modding/Mutagen/wiki/FormKey-Allocation-and-Persistence) developed as a way to track which keys are taken.  Not sure if it would be needed, but something that might potentially come up

# FormID Collisions
The talk so far has been about converting `json<->esp`, but I think there's a few more aspects to consider.

What happens when modder A adds 10 records, and modder B adds 10 records.  They convert to json and commit into Git.  They then push up and merge to master.  Well, the merge might go cleanly according to Git as far as the text file goes (two sections of lines added without conflict), but now the esp will have duplicate FormIDs, as both sides probably allocated the same IDs to their new records.

As such, a tool that is empowering mod systems to be stored in Git might also want to offer a Merge helper tool.  This would essentially notice that the mod on branch A and branch B have FormID conflicts.  It could then load in either A or B, and remap the FormIDs to new values that haven't been taken.  This might be powered by the mod loading/inspection/remapping/persistence tools mentioned earlier.

Probably a good deal of other similar "additional" checks/features that a tool like this might want to offer

# Trailing Blabber
I'm excited someone is interested in these concepts!  I think it would be a large boon to the community to get a tool like this on the ground

All I'll say on that front is that I did develop Mutagen with a lot of care towards not just making it contain features that suit my personal project needs, but attempting to make it a generic and accessible and powerful baseline for downstream projects of all kinds.   The hope was that people could focus on cool downstream projects and make a quicker impact with a modern dev ecosystem without reinventing the wheel for the low level gritty details.  

As you mentioned, serialization/processing isn't owned by anybody.  There's already several that exist (xEdit/SkyProc/Esper/Im sure others).  Mutagen is just another.   If you love Swift and want to develop a tool on top of that, that's awesome as well. 8)

As far as my feedback on the end goal idea: I think it's super interesting, important, and likely doable one way or another

**Comment by samdeane** [comment]
Thanks a lot for engaging! Likewise it's nice to know that I'm not the only one thinking about this stuff...

I think my SwiftESP library is analogous to Mutagen in that it aims to provide a strongly typed data structures / language bindings for each of the record/field types. It uses Swift's native serialisation mechanisms to read/write these in binary format*. 

(*It's a shame I guess that I'm writing in Swift, which is a bit esoteric from the point of view of the modding community. I'd be comfortable in C# or anything else, but Swift is what I do day in day out, and I'd rather focus my efforts on doing something, not on learning another ecosystem :).)


The conversion to/from JSON (or whatever I settle on) is conceptually a layer above SwiftESP, and part of the compiler itself. This is where in theory Mutagen would work just as well:

![Compiler](https://user-images.githubusercontent.com/206306/158800113-0874d46f-2b18-4c59-b15e-063248cf1ef7.png)

Currently the JSON conversion actually lives in SwiftESP, but it will be refactored. It also uses Swift's native serialisation mechanism to read/write the JSON, and like you I'm aiming to optimise the text version to be as compact as possible; simplifying away a lot of the gnarly legacy details of the binary format, and wherever possible providing default values so that you only have to explicitly define properties that differ from the default.

Most of the other features of Mutagen you mentioned are things I'd also like to add. Some logically live in SwiftESP, some in the compiler, but where possible I'd like to keep most of the linting/correctness style stuff at a higher level, which only operates on the text format. It would help to decouple everything and reduce the scope of those tools to something manageable:

![Ecosystem](https://user-images.githubusercontent.com/206306/158800196-0df4cd13-3c2a-45ab-ab9d-86dcfe11e316.png)


In my mind all of this is a step towards a more complete "project" format which would encompass esp records, 3d resources, and scripts, and would build out to ESP/BSA/PEX etc.

![Project](https://user-images.githubusercontent.com/206306/158800251-38a78193-b5fb-4b79-bd1b-e029377f4d8f.png)

You could imagine that sort of tool also having integrations into VSCode, so you can literally just hit Shift-B and have the whole chain kick off and spit out the built mod.

**Comment by samdeane** [comment]
> but where possible I'd like to keep most of the linting/correctness style stuff at a higher level

Having said that, of course, many of those tools require a rich understanding of the data graph, which is what Mutagen/SwiftESP gives access to, so maybe I'm barking up the wrong tree a bit there. 

I'd still like to decouple them though from the main parser. Small and modular FTW...

**Comment by samdeane** [comment]
I hadn't looked at Synthesis & Analyser - they both look interesting too.

On the topic of handling mod patches and collisions, and other things of that ilk, have you seen [this](https://gitlab.com/bmwinger/delta-plugin). I came across it when looking for similar efforts to (de)compile ESPS, but it looks to be focussed more at a being a better way to combine small edits. Which is a worth goal in itself, and also feels like it could be built on top of a common file format / framework.

**Comment by samdeane** [comment]
One of things I struggle with is figuring out where to talk about this stuff. Discord is great, but the ability of everyone to make their own space means we've got potentially hundreds of little atomised communities. 

I feel like it would be really useful if there was one place to go where you might be talking to an audience that included authors of key tools like xEdit, Bodyslide/Outfit Studio, FNIS/Nemesis, key enabling technologies like SKSE and the various body/skin frameworks, major mods, and also at least some of the main creators of clothing/armour and content. Also people working on stuff like the OpenMW and Skyrim Platform.

Does anywhere like that exist?

It's clear that a bunch of people will have thought about this stuff over the years, and I'd like to tap into their wisdom. Even if we end up all doing different implementations, agreeing on the essential features that a text representation would need (if not an actual format itself) would be valuable exercise in its own right.

**Comment by Noggog** [comment]
Sorry I didn't respond.  I imagine I got distracted with other stuff, haha.   Yeah, always hard to find the right community spaces that overlap in the right ways.  I dont know of a single unified place either.

Anyway, I'm going to close this issue, as it's not something that needs work to be done within the Mutagen project.  Feel free to swing by the Mutagen discord if you want to chat in a more back and forth manner.  Cheers!

**Comment by samdeane** [comment]
No problem - I got distracted too 🙃. I am still theoretically interested in it all and might pick up again one day. Partly I'm waiting to see if Starfield advances the state of the art at all (though I am not holding my breath).
