### ISSUE TITLE
Injected Sources As Masters

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#308]
If ModA.esp injects records into Master.esm, and a mod has those injected records, it only views Master.esm as a required mod, when really, ModA.esp is required as well (as it's the source of the injections)

Right now, mod export logic is not aware of any load order concepts, and so cannot recognize this sort of situation.   Perhaps can add an optional export route that is aware of load order with mods, and could do that investigation

**Comment by mrudat** [comment]
As far as I am aware, the entire point of using injected records is so that you don't need to have `ModA.esp` as a dependency.

This is used by not a small number of weapon or armour mods to have optional support for, for example, CCOR or AWKCR. You include the injected records (usually keywords) that target `Master.esm` so that you can reference them in your mod, but because behaviour is only attached to those keywords when you also have CCOR or AWKCR, they have nearly no impact if the defining mods are absent.

Edit: You have no guarantee that, in this circumstance, `ModA.esp` is the defining mod for the injected records without external knowledge, it could have been `ModB.esp`, but because there's no explicit dependency between ModA and ModB by way of using injected records, nothing says ModA or ModB has to be used in a given order.

**Comment by Noggog** [comment]
After talking with Xanza a bit on the side, it sounds like he's in agreement with you.
His goal is going to be achieved via redefining the injection records in his patcher, and also making use of a potential future feature in Synthesis to add an explicit master
https://github.com/Mutagen-Modding/Synthesis/issues/306
