### ISSUE TITLE
Needs a way to convert equality masks into translation masks

### ISSUE THREAD

**Issue by Ricardo-Evans** [Mutagen-Modding/Mutagen#406]
To avoid ITM, lots of checks depend on checking equality first, then decide whether a field needs to be written, which is function of the translation masks. However, I can't find the bridge between equality masks and translation masks.

**Comment by Ricardo-Evans** [comment]
By the way, it seems the generic type parameter of equality masks is useless, since it is always set to bool.

**Comment by Noggog** [comment]
I could see this functionality being useful.  Thanks for the idea!

Few thoughts/questions:
1)  Be aware that the Equals/Hash functionality has not been thoroughly tested.  The generated code should get the bulk of it right, but work has not been put in to confirm 100% correctness yet.  Use with a grain of salt, and definitely let me know if you notice deviations

2)  Can you outline the workflow you're designing that does this?  You've got record A and B, you do equals mask on it, and feed it to a DeepCopy, or some other function?  Just trying to understand the exact goals a bit to see how appropriate/useful this would be, or if there's a similar but different route

3) Equality masks return `Mask<bool>` as `Mask` is a generic class that can be used for other purposes.  `Mask` is just a class that mimics a record, so an `Npc.Mask` might have all the fields that `Npc` does, but they just all happen to be `<T>` where in the case of an equality mask we want all the fields to be of type bool, but someone else with a different design goal might want all the fields to be of type `int`, for whatever whacky goal they might be doing.   `Mask` is intentionally generic to allow anyone to shove in an alternative type for all the fields.

**Comment by Ricardo-Evans** [comment]
Thanks for your reply. Your explanations and remindings are very usefule since they are not mentioned in the documentations.

I'm using mutagen to develop an interactive patcher tool. To explain the workflow, consider some plugins editing the same NPC record: Maybe one of them attaches more scripts to the npc to fix bugs, like what USSEP does; one of them do beautify jobs but the edits are based on the origin skyrim record; the others just do some other unrelated works. Then there is a conflict between these plugins and a merged plugin is needed. I have used some existing workarounds, including Bashed Patch and Mator Smash, but the result is just a mess. Then I think it may needs manual decisions to do the job better, and that's where I use those equality masks: I need to compare records from different plugins and show the difference to users, and convert the user decisions to a translation mask.

**Comment by Ricardo-Evans** [comment]
I also meet another problem during using these masks. It seems there does not exist a method to convert a Mask<T> to a Dictionary<string, T> which contains the fields name and value. I know it's because the existence of MaskItems in the Mask class, but I also find an internal method doing similar jobs to convert a Mask to output strings. I'm just wondering whether the method can be enhanced and exposed.

**Comment by Ricardo-Evans** [comment]
Another issue found:
The field `Scripts` of class `AVirtualMachineAdapter.TranslationMask` should be `ScriptEntry.TranslationMask?[]` instead of `ScriptEntry.TranslationMask?`.
Similar issues are found on field `Properties` of class `ScriptEntry.TranslationMask`. There may be more similar issues. Since these codes seem to be auto-generated, I'm wondering whether the code auto-generation works well.

**Comment by Ricardo-Evans** [comment]
> Another issue found: The field `Scripts` of class `AVirtualMachineAdapter.TranslationMask` should be `ScriptEntry.TranslationMask?[]` instead of `ScriptEntry.TranslationMask?`. Similar issues are found on field `Properties` of class `ScriptEntry.TranslationMask`. There may be more similar issues. Since these codes seem to be auto-generated, I'm wondering whether the code auto-generation works well.

Is it really an issue or misunderstanding? @Noggog

**Comment by Noggog** [comment]
> It seems there does not exist a method to convert a Mask to a Dictionary<string, T>... I'm just wondering whether the method can be enhanced and exposed.

Part of the balance is exposing behaviors that are common enough that many people might use them, vs just making features that are too specific to a single persons needs.  This feels like it might be on the side of a bit too specific to your use case?  I'd have to think on it more.   What string is going into the key?  The name of the field?  A lot of it depends on your specific needs, im thinking?

One tool in the box that synergizes with the strongly typed classes mutagen exposes is C# reflection.  You can inspect a classes API and values via code.  For example, here's someone asking how to print all members that a class had.  
https://stackoverflow.com/questions/852181/c-printing-all-properties-of-an-object
These sorts of concepts can be flexed to do what you want, i imagine.

> The field Scripts of class AVirtualMachineAdapter.TranslationMask should be ScriptEntry.TranslationMask?[] instead of ScriptEntry.TranslationMask?.

I don't think so.  The purpose of a TranslationMask is a reusable mask to instruct what to copy over or write, but not with the granularity of per Script on a list.  It'll have instructions for what to copy on scripts in a VMAD, but not 100 different instructions to match the 100 scripts.   For collection objects, like AVirtualMachineAdapter's Scripts, it's a singular mask for the Scripts, because it's more about "for any/all scripts in this collection, this is what I'll copy/write".   

I think perhaps translation masks might not exactly what you need.   Temptingly applicable, but I think in the end, not quite a fit.    

You say you're making a UI to guide people through merge conflicts?   Are you going to hand design UIs for each class that exists in skyrim?  Or are you going to design them via reflection style concepts (similar to Synthesis' autogenerated setting system)?   If you're doing it via reflection, then it'll be just as easy and similar to do any copies/sets via reflection too, rather than via the mask system.

**Comment by Ricardo-Evans** [comment]
Thanks for your detailed explanations.

> Part of the balance is exposing behaviors that are common enough that many people might use them, vs just making features that are too specific to a single persons needs. This feels like it might be on the side of a bit too specific to your use case? I'd have to think on it more. What string is going into the key? The name of the field? A lot of it depends on your specific needs, im thinking?
> 
> One tool in the box that synergizes with the strongly typed classes mutagen exposes is C# reflection. You can inspect a classes API and values via code. For example, here's someone asking how to print all members that a class had. https://stackoverflow.com/questions/852181/c-printing-all-properties-of-an-object These sorts of concepts can be flexed to do what you want, i imagine.

The field name is expected to be the key. Since the esp files are just about records' name and value, I think there may be common needs on realted APIs. I have considered the reflection approach, but since there is already an internal method doing similar things and the reflection approach may be slower, so I'm just wondering whether the internal method can be exposed. I respect your considerations on exposing APIs carefully, the framework should always aims on the commonly used features.



> I don't think so. The purpose of a TranslationMask is a reusable mask to instruct what to copy over or write, but not with the granularity of per Script on a list. It'll have instructions for what to copy on scripts in a VMAD, but not 100 different instructions to match the 100 scripts. For collection objects, like AVirtualMachineAdapter's Scripts, it's a singular mask for the Scripts, because it's more about "for any/all scripts in this collection, this is what I'll copy/write".

I have understand your designs, and such a behavior is exactly what I need. I'm confused due to the mismatch between equality masks and translation masks. The equality masks seems to use a single bool for each script of AVirtualMachineAdapter, so here comes the problem: Will the order of scripts influnce the compare result? Suppose an AVirtualMachineAdapter with Script1 and Script2, is it same as another AVirtualMachineAdapter with Script2 and Script1?



> You say you're making a UI to guide people through merge conflicts? Are you going to hand design UIs for each class that exists in skyrim? Or are you going to design them via reflection style concepts (similar to Synthesis' autogenerated setting system)? If you're doing it via reflection, then it'll be just as easy and similar to do any copies/sets via reflection too, rather than via the mask system.

The prototype is similar to xEdit when you are comparing edits of the same record from different plugins. Reflection is the last method beyond current designs.

**Comment by Noggog** [comment]
> The field name is expected to be the key. Since the esp files are just about records' name and value

Already this is a bit of preference and use case specific design.  I'd argue records are just about their FormID and values, if anything.   Names (and EditorIDs, too!) are optional in the record definitions, and aren't reliable keys as they can change as mods override content.   Not that you can't have a tool that only cares about named records, but it is relatively specific to you and your tool to want it that way.

Here's an article on why i suggest FormKeys instead of EditorIDs, and I'd say that Name is an even worse choice for a reliable key (given that it's also translated per language)
https://github.com/Mutagen-Modding/Mutagen/wiki/FormLinks-vs-EditorID-as-Identifiers

> Will the order of scripts influnce the compare result? Suppose an AVirtualMachineAdapter with Script1 and Script2, is it same as another AVirtualMachineAdapter with Script2 and Script1?

I mentioned earlier that the equality/hash functionality isn't tested in reliability, yet.  The intention would be any change that would result in different binary when written to disk would mean they're not equal.   This would include order differences.

This is a pretty common problem.  People have a lot of different needs and goals with equality.  There's rarely a one-fits-all for it.  This is why things like IEqualityComparer<T> exist, so people can write their own views of when two objects are equal, and swap those preferences in.   The problem with Mutagen is there's so many different objects that writing custom equality comparers is sort of out of the question.   It's a pretty complex topic, and I don't think Mutagen will be able to offer any extremely powerful and flexible system for allowing small deviations in equality preference any time soon.   I'll of course be thinking on any clever ideas to help people out, but as of now I don't have too many offhand

**Comment by Noggog** [comment]
> The prototype is similar to xEdit when you are comparing edits of the same record from different plugins.  Reflection is the last method beyond current designs.

I do think reflection style approaches are going to work best for you, if I had to guess.  It is slower than hardcoded autogenerated code, but it can be made to be acceptable. 

If you redo all the reflection work for -every- record and -every- field, then it will of course be abysmal performance.

But you can often cache the MethodInfos or other reflection information about the structure of a class, and not do that every time.  You still pay the cost for the GetValue/SetValue calls, but dont pay the "research" half of it every time.

There's another similar concept called C# Expressions, which are a similar but different way to do reflection style jobs.  These can eventually be `Compile()`ed and will yield "real" code that is as fast as prewritten code.  It's a topic that requires lots of knowledge, but it can be powerful.

**Comment by Ricardo-Evans** [comment]
Thank you for your precious advices. I can tell that you are very experienced in C# development, and your explanations make me know better about the designs of Mutagen.

All of my concerns are solved so far, and I think Mutagen is really a good framework to help my job. I will move on my works and let you know if I meet other problems. Thank you for your help again!
