### ISSUE TITLE
Reinvestigate disallowed ModKey chars

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#436]
https://www.nexusmods.com/skyrimspecialedition/mods/26138
![image](https://user-images.githubusercontent.com/24981326/236639077-64222c7a-8f3d-4a0f-a356-0edeb5c5993f.png)
is a mod that has a long dash, which ModKey complained about.   Is this character allowed?  If so, are there others we should allow that we currently arent?

**Comment by studioph** [comment]
Because curiosity got the better of me:

Whatever the issue was with the long dash, it does not appear to be present in recent versions of Mutagen:
![Screenshot_20241121_234200](https://github.com/user-attachments/assets/6acf330c-ae35-4b94-a54c-eb0052ac5fa3)

Also, it looks like the mod was updated shortly after this issue was created to use the normal dash:
![Screenshot_20241121_234506](https://github.com/user-attachments/assets/c667263c-4ed4-4f8d-ab37-b3a4f84f8846)


Regarding the allowed chars, what is present in https://github.com/Mutagen-Modding/Mutagen/blob/72e3d9a1584d090f82c53742f66906f16e595370/Mutagen.Bethesda.Kernel/Plugins/ModKey.cs#L47 seems to align with [Microsoft's own documentation on file naming](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions).

@Noggog My conclusion is that this can be closed unless you want a specific unit test for this scenario or something.

**Comment by Noggog** [comment]
Cool!   Maybe something we'll toss in Analyzers then as a warning
https://github.com/Mutagen-Modding/Mutagen.Bethesda.Analyzers/issues/165
