### ISSUE TITLE
Update Fallout 4's ActorValue Enum with Correct Values

### ISSUE THREAD

**Issue by MarkKoz** [Mutagen-Modding/Mutagen#473]
Currently, Fallout 4's [`ActorValue` enum](https://github.com/Mutagen-Modding/Mutagen/blob/e5319146703ff6c83371627219cf36fee0fd28dd/Mutagen.Bethesda.Fallout4/Enums/ActorValue.cs) is just a copy of Skyrim's, which is not correct/appropriate for Fallout 4.

See the attached CSV files for `AVIF` records' form and editor IDs

[DLCCoast.esm.csv](https://github.com/Mutagen-Modding/Mutagen/files/12446773/DLCCoast.esm.csv)
[DLCNukaWorld.esm.csv](https://github.com/Mutagen-Modding/Mutagen/files/12446774/DLCNukaWorld.esm.csv)
[DLCRobot.esm.csv](https://github.com/Mutagen-Modding/Mutagen/files/12446775/DLCRobot.esm.csv)
[DLCworkshop01.esm.csv](https://github.com/Mutagen-Modding/Mutagen/files/12446776/DLCworkshop01.esm.csv)
[DLCworkshop02.esm.csv](https://github.com/Mutagen-Modding/Mutagen/files/12446777/DLCworkshop02.esm.csv)
[DLCworkshop03.esm.csv](https://github.com/Mutagen-Modding/Mutagen/files/12446778/DLCworkshop03.esm.csv)
[Fallout4.esm.csv](https://github.com/Mutagen-Modding/Mutagen/files/12446779/Fallout4.esm.csv)
[Fallout4.exe.csv](https://github.com/Mutagen-Modding/Mutagen/files/12446780/Fallout4.exe.csv)

**Comment by Noggog** [comment]
xEdit's definitions of the actor value enums are the same for Tes5 and Fallout4
Fo4:  https://github.com/TES5Edit/TES5Edit/blob/dev-4.1.5/Core/wbDefinitionsFO4.pas#L8154
Tes5:  https://github.com/TES5Edit/TES5Edit/blob/dev-4.1.5/Core/wbDefinitionsTES5.pas#L6103

Checked in notepad++ quickly, and they seem to be the same.

But thats the ActorValue enum, and the integer values that represent them on disk.  That's different than the data you're posting, which is the ActorValueInformation Major Records.    The values of the enum don't affect the setup of the major records, or vice versa, as far as I know.  They're generally unrelated, which is why the mapping tech is needed #471 

Can you go over what you think is wrong, specifically?   What is a specific enum value that needs to be different, and for what reasoning?

**Comment by MarkKoz** [comment]
Sorry, I confused the relationship between the records and the enum. I was expecting a one to one mapping like I saw for Skyrim.
